language: node_js
node_js:
        - 12.16.2
deploy:
        provider: elasticbeanstalk
        access_key_id: "$ACCESSKEYID"
        secret_access_key: "$SECRETACCESSKEY"
        region: "us-east-1"
        app: "PKGFND"
        env: "Pkgfnd-env"
        bucket_name: "elasticbeanstalk-us-east-1-236301425402" 
after_deploy:
        - echo "(!!!)done deploying!"
script: "true"
cache:
        directories:
        - "node_modules"
jobs:
        include:
        - stage: "Node App Test"
          script: npm run test
stages:
        - "Node App Test"
before_install:
       - node k_init
